name: Build Linux

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration: [debug, release]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - run: sudo apt install libxrandr-dev
      - run: sudo apt install libxinerama-dev
      - run: sudo apt install libxcursor-dev
      - run: sudo apt install libxi-dev
      - run: sudo apt install libglvnd-dev
      - run: sudo apt install libvulkan-dev
      - run: ./build_linux.sh ${{matrix.configuration}} 